---
title: "Untitled"
author: "Vishekha, Vincent, Nishi and Malik"
date: "11/6/2019"
output: html_document
---
---
title: "Team 3 R Script"
author: "Vishekha, Vincent, Nishi and Malik"
date: "11/5/2019"
output: html_document
---

-------------------------------------#Analyis of pH value of Water for North site#---------------------------------------------------------

```{r}

# Number of observations and number of variables in the data set
dim(North_Site)
#Output
#264 rows   8columns
```


```{r}
# names of all variables in the data set
names(North_Site)
#Output
"Year"             "Site"             "pH"               "Dissolved Oxygen" "Nitrates"         "Total phosphates" "Sulfate"         
"Alkalinity" 
```

```{r}

# Values of the variables in string format 
str(North_Site)
#Output
$ Year            : num  2013 2013 2013 2013 2013 ...
$ Site            : chr  "North" "North" "North" "North" ...
$ pH              : num  8.8 8.7 7.9 8.6 8.7 8.4 8.5 8.1 8.1 8 ...
$ Dissolved Oxygen: num  8.35 8.35 10 13 10 10 11 4.52 5.5 6.52 ...
$ Nitrates        : num  1.32 0.22 2.64 0.0862 4.4 ...
$ Total phosphates: num  0.2 0.52 0.36 0.52 0.22 0.54 0.6 0.52 0.52 0.52 ...
$ Sulfate         : num  75 55 57.5 57.5 50 50 51.5 59 65 52.5 ...
$ Alkalinity      : num  340 280 300 280 280 280 280 270 220 280 ...
```

